spring:
  application:
    name: ribbon-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
